WebHoly/ViewModels/Bible/GenesisViewModel.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace WebHoly.ViewModels.Bible
{
    public class GenesisViewModel
    {
        public List<SelectListItem> Perks { get; set; }
        [Required(ErrorMessage = @"*Required")]
        public int Perk { get; set; }
    }
}

WebHoly/ViewModels/BiblesViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebHoly.ViewModels
{
    public class BiblesViewModel
    {
        public int SChapter { get; set; }
        public int SVrse { get; set; }
        public int EChapter { get; set; }
        public int EVrse { get; set; }
        public string Book { get; set; }

    }
}

WebHoly/Controllers/BibleController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebHoly.Data;
using WebHoly.Models;
using WebHoly.ViewModels.Bible;

namespace WebHoly.Controllers
{
    public class BibleController : Controller
    {
        private readonly ApplicationDbContext _context;
        private Controllers.ApiController _apiController;

        public BibleController(ApplicationDbContext context, ApiController apiController)
        {
            _context = context;
            _apiController = apiController;

        }

        public IActionResult Index()
        {
            List<BookType> bookTypeList = new List<BookType>();

            bookTypeList = _context.BookTypes.ToList();

            bookTypeList.Insert(0, new BookType { Id = 0, Name = "בחר" });

            ViewBag.ListofBookType = bookTypeList;
            return View();
        }
        [HttpPost]
        public async Task<JsonResult> IndexAsync(BookType objbookType )
        {
            if(objbookType.Id ==0)
            {
                ModelState.AddModelError("", "בחר קטגוריה");
            }
            else if (objbookType.BookId == 0)
            {
                ModelState.AddModelError("", "בחר ספר");
            }
            else if (objbookType.EpisodeId == 0)
            {
                ModelState.AddModelError("", "בחר פרק");
            }
            var bookName = _context.Books.Find(objbookType.BookId).SubName;
            var episodeNumber = _context.Episodes.Find(objbookType.EpisodeId).Number;

            var item = await _apiController.BibleApichapter(episodeNumber, bookName);
            var a = 3;

            return Json(new { Success = true, Item = item });
        }

        public JsonResult GetBook(int BookTypeId)
        {
            List<Book> bookList = new List<Book>();

            bookList = _context.Books.Where(x => x.BookTypeId == BookTypeId).ToList();
            bookList.Insert(0, new Book { Id = 0, Name = "בחר" });

            return Json(new SelectList(bookList, "Id", "Name"));
        }

        public JsonResult GetEpisode(int BookId)
        {
            List<Episode> bookList = new List<Episode>();

            bookList = _context.Episodes.Where(x => x.BookId == BookId).ToList();
            bookList.Insert(0, new Episode { Id = 0, Number = 0 });

            return Json(new SelectList(bookList, "Id", "Number"));
        }

        //public void AddBooksType()
        //{
        //    List<BookType> booksType = new List<BookType>()
        //    {
        //        new BookType
        //        {
        //            Name = "תורה",
        //            Type = "חמישה חומשי תודה"
        //        },
        //        new BookType
        //        {
        //            Name = "נביאים",
        //            Type = "שמונה ספרים"
        //        },
        //        new BookType
        //        {
        //            Name = "כתובים",
        //            Type = "אחד עשר ספרים"
        //        }
        //    };
        //    _context.AddRange(booksType);
        //    _context.SaveChanges();
        //}


        //public void AddBooks()
        //{
        //    List<Book> books = new List<Book>()
        //    {
        //        new Book
        //        {
        //            Name = "בְּרֵאשִׁית",
        //            SubName = "ge",
        //            BookTypeId = 1
        //        },
        //        new Book
        //        {
        //            Name = "שְׁמוֹת",
        //            SubName = "exo",
        //            BookTypeId = 1
        //        },
        //        new Book
        //        {
        //             Name = "וַיִּקְרָא",
        //            SubName = "lev",
        //            BookTypeId = 1
        //        },
        //        new Book
        //        {
        //             Name = "בְּמִדְבַּר",
        //            SubName = "num",
        //            BookTypeId = 1
        //        },
        //        new Book
        //        {
        //             Name = "דברים",
        //            SubName = "deu",
        //            BookTypeId = 1
        //        },
        //        new Book
        //        {
        //             Name = "יְהוֹשֻׁעַ",
        //            SubName = "josh",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "שופטים",
        //            SubName = "jdgs",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "שְׁמוּאֵל א",
        //            SubName = "1sm",
        //            BookTypeId = 2
        //        },
        //         new Book
        //        {
        //             Name = " שְׁמוּאֵל ב",
        //            SubName = "2sm",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = " מְלָכִים א",
        //            SubName = "1ki",
        //            BookTypeId = 2
        //        }, 
        //        new Book
        //        {
        //             Name = "מְלָכִים ב",
        //            SubName = "2ki",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "יְשַׁעְיָהוּ",
        //            SubName = "isa",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "יִרְמְיָהוּ",
        //            SubName = "jer",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "יְחֶזְקֵאל",
        //            SubName = "eze",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "הוֹשֵׁעַ",
        //            SubName = "hos",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "יוֹאֵל",
        //            SubName = "joel",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "עָמוֹס",
        //            SubName = "amos",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "עֹבַדְיָה",
        //            SubName = "obad",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "יוֹנָה",
        //            SubName = "jonah",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "מִיכָה",
        //            SubName = "mic",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "נַחוּם",
        //            SubName = "nahum",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "חֲבַקּוּק",
        //            SubName = "hab",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "צְפַנְיָה",
        //            SubName = "zep",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "חַגַּי",
        //            SubName = "heg",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "זְכַרְיָה",
        //            SubName = "zec",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "מַלְאָכִי",
        //            SubName = "mal",
        //            BookTypeId = 2
        //        },
        //        new Book
        //        {
        //             Name = "דִּבְרֵי הַיָּמִים א",
        //            SubName = "1chr",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "דִּבְרֵי הַיָּמִים ב",
        //            SubName = "2chr",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "תְּהִלִּים",
        //            SubName = "psa",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "אִיּוֹב",
        //            SubName = "job",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "מִשְׁלֵי",
        //            SubName = "prv",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "רוּת",
        //            SubName = "ruth",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "שִׁיר הַשִּׁירִים",
        //            SubName = "ssol",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "קֹהֶלֶת",
        //            SubName = "eccl",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "אֵיכָה",
        //            SubName = "lam",
        //            BookTypeId = 3
        //        },
        //        new Book
        //        {
        //             Name = "אֶסְתֵּר",

WebHoly/Views/Bible/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model WebHoly.Models.BookType



<div id="check">

    <form id="myForm" asp-controller="Bible" asp-action="Index" method="post" class="" role="form">
        <div class="form-group">
            <div class="row">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <div class="col-xl-12 col-sm-6 col-md-5 col-lg-4">
                    <label asp-for="Name" class="control-label"></label>
                    <select asp-for="Id" class="form-control" asp-items="@(new SelectList(ViewBag.ListofBookType, "Id", "Name"))"></select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="col-xl-12 col-sm-6 col-md-5 col-lg-4">
                    <label class="control-label"> ספר</label>
                    <select class="form-control" id="BookId" name="BookId" asp-for="BookId" asp-items="@(new SelectList(string.Empty, "Id", "Name"))"></select>
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="row">
                <div class="alert-danger" asp-validation-summary="ModelOnly"></div>
                <div class="col-xl-12 col-sm-6 col-md-5 col-lg-4">
                    <label class="control-label"> פרק</label>
                    <select class="form-control" id="EpisodeId" name="EpisodeId" asp-for="EpisodeId" asp-items="@(new SelectList(string.Empty, "Id", "Number"))"></select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="row">
                <div class="col-xl-12 col-sm-6 col-md-5 col-lg-4">
                    <input type="button" value="מצא" onclick="AjaxFormSubmit()" />
                </div>
            </div>
        </div>
    </form>
    <div class=" box">
        <div class="card">
            <div class="leftbox">
                <div class="row bible ">
                    <span id="lblName"></span>
                </div>
            </div>
        </div>
    </div>

</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

<script src="/lib/jquery/dist/jquery.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        var items = "<option value='0'>בחר</option>";
        $('#BookId').html(items);
        $('#EpisodeId').html(items);
    });

</script>

<script type="text/javascript">
    $(document).ready(function () {
        $('#Id').change(function () {
            var url = '@Url.Content("~/")' + "Bible/GetBook";
            var ddlsource = "#Id";
            $.getJSON(url, { BookTypeId: $(ddlsource).val() }, function (data) {
                var items = '';
                $("#BookId").empty();
                $.each(data, function (i, book) {
                    items += "<option value ='" + book.value + "'>" + book.text + "</option>";
                });
                $('#BookId').html(items);
            });
        });
    });
     $(document).ready(function () {
         $('#BookId').change(function () {
             var url = '@Url.Content("~/")' + "Bible/GetEpisode";
             var ddlsource = "#BookId";
             $.getJSON(url, { BookId: $(ddlsource).val() }, function (data) {
                var items = '';
                 $("#EpisodeId").empty();
                 $.each(data, function (i, episode) {
                     items += "<option value ='" + episode.value + "'>" + episode.text + "</option>";
                });
                 $('#EpisodeId').html(items);
            });
        });
    });

    function AjaxFormSubmit() {
        //Set the URL.
        var url = $("#myForm").attr("action");

        //Add the Field values to FormData object.
        var formData = new FormData();
        formData.append("BookId", $("#BookId").val());
        formData.append("EpisodeId", $("#EpisodeId").val());
        formData.append("Id", $("#Id").val());
        $.ajax({
            type: 'POST',
            url: url,
            data: formData,
            processData: false,
            contentType: false
        }).done(function (response) {
            if (response.Status) {
                console.log("blalba");
            }
            else {
                console.log(response);
                $("#lblName").html(response.item);


            }
        });
    }




</script>

<style>
    .form-group {
        font-size: 1.0em;
    }

    .bible {
        box-sizing: content-box;
        width: 100%;
        padding: -5px 15px 0px 0px;
    }

    #lblName {
        box-sizing: border-box;
        padding: 0px 0px 0px 10px !important;
        text-align: right;
        width: 100%;
        margin-bottom:5px;
        margin-top:5px;
    }
    #check {
        text-align: right;
        padding: 0px 0px 0px 10px !important;
    }
</style>